pipeline {
    agent {
        label 'desktop'
    }

    stages {
        stage ('Get latest') {
            def server
            def downloadSpec = """{
             "files": [
              {
                  "pattern": "mtgo-best-bot-releases/*.jar",
                  "target": "mtgo-best-bot/"
                }
             ]
            }"""

            server = Artifactory.server 'localhost'
            server.download(downloadSpec)
        }
    }
}